### ISSUE TITLE
Add tqdm to setup.py

### ISSUE THREAD

**Issue by martijnende** [HMZ-03/DASPy#1]
Hello. I noticed that the `tqdm` library is not included in the [`install_requires`](https://github.com/HMZ-03/DASPy/blob/main/setup.py#L35) list, which raises an error when importing `daspy`. After installing `tqdm` manually, everything is fine.

**Comment by HMZ-03** [comment]
Thanks a lot for your reminder. Now tqdm library is included in the install_requires list.
